 apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
 kind: Ingress
 metadata:
   name: ecom-ingress
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: ecom.server
     http:
       paths:
       - path: /user
         backend:
           serviceName: user-service 
           servicePort: 30003
