apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: user-service
 namespace: default
spec:
 template:
  spec:
   containers:
    - image: dev.local/user-service:latest
      name:  user-svc
      imagePullPolicy: Never
      env:
        - name: spring.data.mongodb.host
          value: mongodb-svc
